delete useless, update runtool script

diff --git a/runtool b/runtool
--- a/runtool
+++ b/runtool
@@ -5,19 +5,26 @@
 
 
 ## SETTINS
-BASEURL=http://autoserver:8000/testtools
+BASEURL=http://autoserver:8000/tools
+RUNSLEEP=10
 
 
 installpkg(){
 #	[ -z $PACKAGES ] && return 0
         local i
+	local inst_ok
         echo "Checking packages ..."
         for i
         do
                 rpm -qi $i &> /dev/null || \
-                        yum install $i -y &> /dev/null || \
-                        echo "WARNING: yum insatll $i failed, related cases may return FAIL."
+                        yum install $i -y &> /dev/null 
+			if [ $? == 0 ]; then
+				inst_ok="$instok $i"
+			else
+				echo "WARNING: yum insatll $i failed, related cases may return FAIL."
+			fi
         done
+	echo "PACKAGES=$inst_ok" >> $RESULTDIR/$TOOLNAME
 }
 
 get_tarball() {
@@ -31,6 +38,8 @@ get_tarball() {
 			exit 1
 		}
 	}
+	echo "URL=$URL" >> $RESULTDIR/$TOOLNAME
+	echo "TARBALL=$TARBALL" >>  $RESULTDIR/$TOOLNAME
 
 	[ -f $TARBALL.$MD5SUFFIX ] || \
 	{
@@ -44,6 +53,7 @@ get_tarball() {
 	}
 	local expect_md5=`cat $TARBALL.$MD5SUFFIX | cut -d " " -f 1`
 	local actrual_md5=`md5sum $TARBALL | cut -d " " -f 1`
+	echo "MD5=$actrual_md5" >> $RESULTDIR/$TOOLNAME
 	[ $expect_md5 == $actrual_md5 ] || \
 	{
 		echo "WARN: $TARBALL has different MD5 than expected."
@@ -69,11 +79,11 @@ install() {
 	[ -f $TARBALL ] || \
 		get_tarball
 	if [ x$TARGET != x ]; then
-        	if [ -d $TARGET ] || [ -f $TARGET ]; then
-	        	echo "ERROR: $TARGET already exist"
+        	if [ -e $TARGET ] ; then
+	        	echo "WARN: $TARGET already exist"
 		        echo "Change target in $TOOLNAME test config file"
 		        echo "Or stop install and use the already exit."
-             		exit 1
+             		return 1
 	        fi
 	fi
 	local tarball=$TARBALL
@@ -81,7 +91,9 @@ install() {
 	local arch=`arch`
 	local folder=$FOLDER
 	local cmd=$INSTALLCMD
-	local date_end=`date +%Y_%m_%d_%Hh_%M_%S`
+
+	echo "TARGET=$TARGET" >> $RESULTDIR/$TOOLNAME
+	echo "INSTALLCMD=\"$cmd\"" >> $RESULTDIR/$TOOLNAME
 
 	if (is_sub_item $suffix "tar gz bz2 xz tgz"); then
 		tar xf $tarball
@@ -103,16 +115,57 @@ install() {
 }
 
 runtest() {
-	[ -d $TARGET ] || \
+	[ -e $TARGET ] || \
 		install
-	local cmd=$RUNCMD
+	local times=$RUNTIME
+	local t=
+
+	for t in `seq $times`
+	do
+		echo "INFO: ${TOOLNAME} test ($t/$times)"
+		local prefix=RUNCMD
+		local i=1
+		local cmd=$prefix$i
+
+		while [ "x${!cmd}" != "x" ]
+		do
+			echo "INFO: running cmd: ${!cmd}"
+			# echo "$cmd=${!cmd}" >> $RESULTDIR/${TOOLNAME}
+			sleep $RUNSLEEP
+			eval ${!cmd} &>> $RESULTDIR/${TOOLNAME}_${cmd}.log
+			i=$((i+1))
+			cmd=$prefix$i
+		done
+	done
+
+	echo "RUNTIME=$times" >> $RESULTDIR/$TOOLNAME
+
+	local j=1
+	while [ $j -lt $i ]
+	do
+		c=RUNCMD$j
+		echo "RUNCMD$j=\"${!c}\"" >> $RESULTDIR/$TOOLNAME
+		j=$((j+1))
+	done
+	echo "INFO: test run finished, check results at: $RESULTDIR"
+
+: '	
+	local oldifs=$IFS
+	IFS=","
+	local j=
 	echo "INFO: run test"
-	echo "INFO: $cmd"
-	eval $cmd &> $RESULTDIR/${TOOLNAME}_runtest.log
+	for j in $cmds
+	do
+		echo "INFO: running cmd is: $j"
+		eval $j &> $RESULTDIR/${TOOLNAME}_.log
+	done
+	IFS=$oldifs
+	
+	'
 }
 
 runstress() {
-	[ -d $TARGET ] || \
+	[ -e $TARGET ] || \
 		install
 	local cmd=$STRESSCMD
 	echo "INFO: run stress"
@@ -135,6 +188,8 @@ run() {
 		local date_end=`date +%Y_%m_%d_%Hh_%M_%S`
 		RESULTDIR=${RESULT:-$TOOLNAME}_$date_end
 		mkdir -p $RESULTDIR
+		echo "# RESULTDIR=$RESULTDIR" >> $RESULTDIR/${TOOLNAME}
+		echo "TOOLNAME=$TOOLNAME" >> $RESULTDIR/${TOOLNAME}
 		[ -d $RESULTDIR ] || \
 		{
 			echo "ERROR: failed to create $RESULTDIR"
@@ -157,11 +212,14 @@ generate() {
 #
 # This file is generated by $0
 # You should edit this file before you run the test.
+PACKAGES=
 
 # base url of tarball
 BASEURL=$BASEURL
 # test name, same as file name by default.
 TOOLNAME=$testfile
+# sleep time in seconds before run test.
+RUNSLEEP=$RUNSLEEP
 # suffix of md5 file
 MD5SUFFIX=md5
 # test version
@@ -173,33 +231,37 @@ TARBALL=
 # tarball url, 
 URL=\$BASEURL/\$TARBALL
 # folder after untar
-FOLDER=
+FOLDER=\${TARBALL%%.*}
 # patch file
 PATCH=\${TOOLNAME}.patch
-# install destination, directory
+# install destination
 TARGET=
 
 
 INSTALLCMD=
-RESULTS=
-RUNCMD=
+RESULT=
+# RUNCMD would be expanded with increasing suffix.
+RUNCMD1=
+
+# stress for running command cycally until specific time.
 STRESSCMD=
+RUNTIME=1
 eof
 }
 
 usage() {
 	cat << eof
-USAGE: $0 <option> <test> [<test1> ...] 
+USAGE: $0 <option> <testfile> [<testfile1> ...] 
 
 OPTIONS:
     get        get test tarball
-    install    install TESTTOOL
-    test       run test
+    install    install test
+    run        run test
     stress     run stress test
     generate   gernerate test file
     help       show usage
 
-TEST:
+TESTFILE:
     Particular file for define the test.
     The basic formart can be generated by:
 
@@ -218,7 +280,7 @@ main(){
         case $option in
                 "install")
 			run install $@ ;;
-                "test")
+                "run")
 			run runtest $@ ;;
                 "stress")			
                         run runstress $@ ;;
