upgrade runtool.

diff --git a/runtool b/runtool
--- a/runtool
+++ b/runtool
@@ -21,10 +21,10 @@ installpkg(){
 			if [ $? == 0 ]; then
 				inst_ok="$instok $i"
 			else
-				echo "WARNING: yum insatll $i failed, related cases may return FAIL."
+				echo "WARNING: yum install $i failed, related cases may return FAIL."
 			fi
         done
-	echo "PACKAGES=$inst_ok" >> $RESULTDIR/$TOOLNAME
+	echo "PACKAGES=\"$inst_ok\"" >> $RESULTDIR/$TOOLNAME
 }
 
 get_tarball() {
@@ -103,7 +103,7 @@ install() {
 		echo "WARN: unkown type: $tarball"
 	#	return 1
 	fi
-	[ -z $PATCH ] || patch -p0 $PATCH
+	[ -z $PATCH ] && patch -p0 $PATCH
 	echo "INFO: install $TOOLNAME"
 	echo "INFO: $cmd"
 	eval $cmd &> $RESULTDIR/${TOOLNAME}_install.log || \
@@ -177,6 +177,11 @@ run() {
 	local op=$1
 	shift
 	local testfiles=$1
+	[ x$testfiles != "x" ] || {
+		echo "No testfile specified. "
+	        return 4
+	}
+
 	for i in `echo $testfiles | tr "," " "`
 	do
 		source $i || \
@@ -199,7 +204,7 @@ run() {
 	done
 }
 
-generate() {
+gentest() {
 	local testfile=$1
 	[ ! -f $testfile ] || \
 	{
@@ -207,13 +212,14 @@ generate() {
 		exit 1
 	}
 	cat > $testfile << eof
-# name: $testfile
-# date: $(date)
+# name: `basename $testfile`
+# date: `date`
 #
 # This file is generated by $0
-# You should edit this file before you run the test.
-PACKAGES=
+# You should edit this file before run the test.
 
+# packages need to be install before installation
+PACKAGES=""
 # base url of tarball
 BASEURL=$BASEURL
 # test name, same as file name by default.
@@ -237,7 +243,8 @@ PATCH=\${TOOLNAME}.patch
 # install destination
 TARGET=
 
-
+# test loop times.
+RUNTIME=1
 INSTALLCMD=
 RESULT=
 # RUNCMD would be expanded with increasing suffix.
@@ -245,7 +252,6 @@ RUNCMD1=
 
 # stress for running command cycally until specific time.
 STRESSCMD=
-RUNTIME=1
 eof
 }
 
@@ -258,7 +264,9 @@ OPTIONS:
     install    install test
     run        run test
     stress     run stress test
-    generate   gernerate test file
+    gentest    generate test file
+    gendoc     generate test document
+    genrep     generate test report with given result directory
     help       show usage
 
 TESTFILE:
@@ -270,7 +278,29 @@ TESTFILE:
 eof
 }
 
+# generate document of test
 gendoc() {
+	DOCUMENT=${DOCUMENT-$TOOLNAME.md}
+	cat > $DOCUMENT << eof
+## Before Install
+\`\`\`
+yum install -y $PACKAGES
+\`\`\`
+
+## Installation
+\`\`\`
+`echo $INSTALLCMD | tr ";" "\n"`
+\`\`\`
+
+## Running test
+\`\`\`
+`echo $RUNCMD1 | tr ";" "\n"`
+\`\`\`
+eof
+}
+
+# generate report
+genrep() {
 	:
 }
 
@@ -286,12 +316,18 @@ main(){
                         run runstress $@ ;;
 		"get")
 			run get_tarball $@ ;;
-		"generate")
-			generate $@ ;;
+		"gentest")
+			gentest $@ ;;
+		"gendoc")
+			run gendoc $@ ;;
+		"genrep")
+			genrep $@ ;;
                 ""|* )
                         usage ;;
         esac
 }
 
 
-main $@
+if [ $0 == "./runtool" ] ; then
+	main $@
+fi
